# Generated by Django 5.0.7 on 2024-08-15 17:02

import ToDoListApp.models.task
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='new-list', max_length=100, validators=[ToDoListApp.models.task.validate_title], verbose_name='عنوان')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_do_lists', to=settings.AUTH_USER_MODEL, verbose_name='صاحب')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='new-task', max_length=100, validators=[ToDoListApp.models.task.validate_title], verbose_name='عنوان')),
                ('description', models.CharField(default='', max_length=1000, verbose_name='توضیحات')),
                ('deadline', models.DateField(default=datetime.date(2024, 8, 15), max_length=10, validators=[ToDoListApp.models.task.validate_date], verbose_name='زمان سرسید')),
                ('priority', models.CharField(choices=[('1', 'High'), ('2', 'Medium'), ('3', 'Low')], default='2', max_length=1, validators=[ToDoListApp.models.task.validate_priority], verbose_name='اولویت')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='media_files', verbose_name='فایل ضمیمه')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='صاحب')),
                ('users_shared_with', models.ManyToManyField(related_name='tasks_shared_with_user', to=settings.AUTH_USER_MODEL, verbose_name='افرادی که با آنها به اشتراک گذاشته شده')),
                ('to_do_lists', models.ManyToManyField(related_name='tasks', to='ToDoListApp.todolist', verbose_name='لیست\u200cها')),
            ],
        ),
    ]
