# Generated by Django 5.0.7 on 2024-08-14 07:07

import ToDoListApp.models.task2
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoListApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task2',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='فایل ضمیمه'),
        ),
        migrations.AlterField(
            model_name='task2',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now, max_length=10, validators=[ToDoListApp.models.task2.validate_date], verbose_name='زمان سرسید'),
        ),
        migrations.AlterField(
            model_name='task2',
            name='description',
            field=models.CharField(default='', max_length=1000, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='task2',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='صاحب'),
        ),
        migrations.AlterField(
            model_name='task2',
            name='priority',
            field=models.CharField(choices=[('1', 'High'), ('2', 'Medium'), ('3', 'Low')], default='2', max_length=1, validators=[ToDoListApp.models.task2.validate_priority], verbose_name='اولویت'),
        ),
        migrations.AlterField(
            model_name='task2',
            name='title',
            field=models.CharField(default='new-task', max_length=100, validators=[ToDoListApp.models.task2.validate_title], verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='task2',
            name='to_do_lists',
            field=models.ManyToManyField(related_name='tasks', to='ToDoListApp.todolist2', verbose_name='لیست\u200cها'),
        ),
        migrations.AlterField(
            model_name='task2',
            name='users_shared_with',
            field=models.ManyToManyField(related_name='tasks_shared_with_user', to=settings.AUTH_USER_MODEL, verbose_name='افرادی که با آنها به اشتراک گذاشته شده'),
        ),
        migrations.AlterField(
            model_name='todolist2',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='to_do_lists', to=settings.AUTH_USER_MODEL, verbose_name='صاحب'),
        ),
        migrations.AlterField(
            model_name='todolist2',
            name='title',
            field=models.CharField(default='new-list', max_length=100, validators=[ToDoListApp.models.task2.validate_title], verbose_name='عنوان'),
        ),
    ]
