# Generated by Django 5.0.7 on 2024-08-15 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoListApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
