# Generated by Django 5.0.7 on 2024-08-14 07:12

import ToDoListApp.models.task2
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoListApp', '0002_task2_attachment_alter_task2_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task2',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2024, 8, 14, 7, 12, 39, 253544, tzinfo=datetime.timezone.utc), max_length=10, validators=[ToDoListApp.models.task2.validate_date], verbose_name='زمان سرسید'),
        ),
    ]
