# Generated by Django 5.0.7 on 2024-08-17 11:44

import ToDoListApp.models.task
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoListApp', '0002_delete_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=datetime.date(2024, 8, 17), max_length=10, validators=[ToDoListApp.models.task.validate_date], verbose_name='زمان سرسید'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='توضیحات'),
        ),
    ]
