# Generated by Django 5.0.7 on 2024-08-29 17:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoListApp', '0005_task_users_who_can_see_alter_task_deadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='users_who_can_see',
            field=models.ManyToManyField(null=True, related_name='shared_added_tasks', to=settings.AUTH_USER_MODEL, verbose_name='کاربرانی که فقط تسک را می\u200cبینند'),
        ),
    ]
