# Generated by Django 4.2.11 on 2024-08-11 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ToDoListApp', '0007_todolist2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task2',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('deadline', models.DateField()),
                ('priority', models.CharField(choices=[('1', 'High'), ('2', 'Medium'), ('3', 'Low')], max_length=6)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('to_do_lists', models.ManyToManyField(related_name='tasks', to='ToDoListApp.todolist2')),
                ('users_shared_with', models.ManyToManyField(related_name='tasks_shared_with_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
