from my_app.views import create_list_view
from my_app.views import create_task_view
from my_app.views import delete_list_view
from my_app.views import delete_task_view
from my_app.views import edit_list_view
from my_app.views import edit_task_view
from my_app.views import get_list_view
from .get_task_view import get_task
from .register_view import register_user
