from .add_shared_tasks_view3 import AddSharedTasks3
from .create_list_view3 import CreateList3
from .create_task_view3 import CreateTask3
from .delete_list_view3 import DeleteList3
from .delete_task_view3 import DeleteTask3
from .edit_list_view3 import EditList3
from .edit_task_view3 import EditTask3
from .get_list_view3 import GetList3
from .get_task_view3 import GetTask3
from .login_view3 import Login3
from .register_login_view3 import RegisterLogin3
from .register_view3 import Register3
from .share_task_view3 import ShareTask3
from .show_lists_view3 import ShowLists3
